import { createSlice } from '@reduxjs/toolkit';

const initialAuthState = {
  isAuthenticated: false,
  currentUser: null,
  registerSuccess: false,
  users: [
    { id: 1, name: 'Amcovad', email: 'info@amcovad.com', password: '123456' },
    { id: 2, name: 'Admin', email: 'admin@amcovad.com', password: 'abcdef' }
  ],
  errors: ''
};

export const authSlice = createSlice({
  name: 'auth',
  initialState: initialAuthState,
  reducers: {
    login: (state, action) => {
      const { email, password } = action.payload;
      const user = state.users.filter((user) => user.email === email && user.password === password);

      if (user.length > 0) {
        state.isAuthenticated = true;
        state.currentUser = user[0];
      } else {
        state.isAuthenticated = false;
        state.errors = 'invalid Email or Password';
      }
    },
    logout: (state) => {
      state.isAuthenticated = false;
    },
    signup: (state, action) => {
      const { email } = action.payload;
      //check email exist in users
      const userExists = state.users.filter((user) => user.email === email);
      if (userExists.length > 0) {
        state.errors = 'Email already exist';
      } else {
        state.users.push({
          id: state.users.length + 1,
          ...action.payload
        });
        state.registerSuccess = true;
      }
    }
  }
});

export const { login, logout, signup } = authSlice.actions;

export default authSlice.reducer;

//https://www.figma.com/file/7P77BuyOwuoMaFp5qnXgsB/Untitled?node-id=1%3A47
// Use the low fidelity design as guideline, please reuse everything we have in amcovad to save time
// emphasis should be made on the logic not the UI
//
// create a slice to do online shopping
// item has the following fields:
// id(autogenerated), name, image(optional, use a default image url if not given) , price
// user should be able to click on favorite to see all items marked as favorite
// first page: add an item
// items page: to view all items (items can be clicked on to edit and mark as favorite)
// favorites page: to see all items marked as favorite
// 1. add an item to the list
// 2. remove an item from the list
// 3. update an existing item
// 4. mark an item as favorite
// 5. clear the list
